<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="/styles/styles.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <!-- Sidebar -->
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <a class="navbar-brand">
                        Chippy Digital
                    </a>
                    <li class="nav-item">
                        <!-- Navbar Items -->
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Main Content -->
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 main-content">
            <!-- Add a button to toggle the sidebar on small screens -->
            <button class="btn btn-primary d-md-none" type="button" data-toggle="collapse" data-target=".sidebar">
                Toggle Sidebar
            </button>

            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h2>QuickNote</h2>
            </div>
            <div class="card">
                <div class="card-header">
                    Notes
                </div>
                <div class="card-body" id="note-window">
                    <!-- Notes should appear here -->
                </div>
                <div class="card-footer">
                    <div class="input-group">
                        <input type="text" class="form-control" id="note-input" placeholder="Enter note here...">
                        <button class="btn btn-primary" id="note-submit">Submit</button>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>
